# environment-mapping.yaml - update as required depending on project needs
---
- branchNamePattern: '(feature|bugfix|hotfix)/.*'
  environment: 'PREDEV'
- branchNamePattern: 'develop'
  environment: 'DEV'
- branchNamePattern: 'main'
  environment: 'PROD'
