# This file provides configuration for execution to be run in parallel
# for Robot Tests. It provides with a mechanism to specify variables
# that are to be used for parallel configuration. The variables override
# default execution variables. Also in case that are default execution
# parameteres are not specified in the config they are taken from default.
---
instances:
  - AppiumServer: http://eu1.appium.testobject.com/wd/hub
    AndroidPlatformName: Android
    AndroidPlatformVersion: 9
    AndroidDeviceName: Google_Pixel_2_real
    PhoneOnly: false
    TabletOnly: false
    privateDeviceOnly: false
    TestObjectApiKey: 1234
    AppiumVersion: 1.14.0
    env: SauceReal
  - AppiumServer: http://eu1.appium.testobject.com/wd/hub
    AndroidPlatformName: Android
    AndroidPlatformVersion: 8
    AndroidDeviceName: Google_Pixel_2_XL_real
    PhoneOnly: false
    TabletOnly: false
    privateDeviceOnly: false
    TestObjectApiKey: 123
    AppiumVersion: 1.14.0
    env: SauceReal
