# environment-mapping.yaml
---
- branchNamePattern: '(feature|bugfix|hotfix)/.*'
  environment: 'PREDEV'
- branchNamePattern: 'develop'
  environment: 'DEV'
- branchNamePattern: 'release/qa'
  environment: 'QA'
- branchNamePattern: 'master'
  environment: 'PROD'
- branchNamePattern: 'preqa'
  environment: 'PREQA'
